"""Storage backends for the CodeBridge RAG layer."""

from .embedding_cache import (
    DEFAULT_TEXT_EMBEDDING_CACHE_FILENAME,
    TEXT_EMBEDDING_CACHE_SCHEMA_VERSION,
    TEXT_EMBEDDING_CACHE_TABLE,
    TextEmbeddingCache,
    TextEmbeddingCacheError,
    TextEmbeddingCacheIntegrityError,
    TextEmbeddingCacheVersionError,
    connect_text_embedding_cache,
    initialize_text_embedding_cache,
    resolve_text_embedding_cache_path,
)
from .fts5 import (
    FTS_INDEXED_FIELDS,
    FTS_LAYOUT_VERSION,
    FTS_METADATA_FIELDS,
    FTS_TABLE,
    REQUIRED_FTS_TRIGGERS,
    RagFts5IntegrityError,
    RagFts5UnavailableError,
    fts5_available,
    fts5_table_exists,
    fts5_trigger_names,
    initialize_fts5,
    rebuild_fts5,
    verify_fts5_integrity,
)
from .lexical_ranking import (
    LEXICAL_BM25_WEIGHTS,
    LEXICAL_RETRIEVAL_MODE,
    lexical_score_from_bm25,
    search_lexical_ranked,
)
from .lexical_search import (
    LexicalSearchHit,
    RagLexicalQueryError,
    search_lexical,
)
from .sqlite_schema import (
    DEFAULT_DATABASE_FILENAME,
    REQUIRED_TABLES,
    SCHEMA_VERSION,
    RagSchemaIntegrityError,
    RagSchemaVersionError,
    connect_rag_index,
    initialize_rag_schema,
    schema_table_names,
)

__all__ = [
    "DEFAULT_TEXT_EMBEDDING_CACHE_FILENAME",
    "TEXT_EMBEDDING_CACHE_SCHEMA_VERSION",
    "TEXT_EMBEDDING_CACHE_TABLE",
    "TextEmbeddingCache",
    "TextEmbeddingCacheError",
    "TextEmbeddingCacheIntegrityError",
    "TextEmbeddingCacheVersionError",
    "connect_text_embedding_cache",
    "initialize_text_embedding_cache",
    "resolve_text_embedding_cache_path",
    "FTS_INDEXED_FIELDS",
    "FTS_LAYOUT_VERSION",
    "FTS_METADATA_FIELDS",
    "FTS_TABLE",
    "REQUIRED_FTS_TRIGGERS",
    "RagFts5IntegrityError",
    "RagFts5UnavailableError",
    "fts5_available",
    "fts5_table_exists",
    "fts5_trigger_names",
    "initialize_fts5",
    "rebuild_fts5",
    "verify_fts5_integrity",
    "LEXICAL_BM25_WEIGHTS",
    "LEXICAL_RETRIEVAL_MODE",
    "lexical_score_from_bm25",
    "search_lexical_ranked",
    "LexicalSearchHit",
    "RagLexicalQueryError",
    "search_lexical",
    "DEFAULT_DATABASE_FILENAME",
    "REQUIRED_TABLES",
    "SCHEMA_VERSION",
    "RagSchemaIntegrityError",
    "RagSchemaVersionError",
    "connect_rag_index",
    "initialize_rag_schema",
    "schema_table_names",
]
